package rules;
import com.drools.si.Dialog
import com.drools.si.QuestionWithAnswer
import com.drools.si.Helper
import java.util.Collections
dialect  "mvel"

rule "IsTheTalentWillingToMoveNearYourPlaceOfBusiness"
when
    qa : QuestionWithAnswer(getQuestion() == "Is the talent willing to move near your place of business?", getAnswer() == Helper.EMPTY_STRING)
then
    Dialog.showDialogWithQuestion(qa);
    QuestionWithAnswer newQuestion = new QuestionWithAnswer(qa);
    insert(newQuestion);
end

rule "IsTheTalentWillingToMoveNearYourPlaceOfBusinessNo"
when
    qa : QuestionWithAnswer(getQuestion() == "Is the talent willing to move near your place of business?", getAnswer() == Helper.YES)
then
    QuestionWithAnswer newQuestion = new QuestionWithAnswer("Are they more efficient workers when they wear sweatpants and sit in their La-Z-Boy?");
    newQuestion.addBoolAnswers();
    insert(newQuestion);
end

rule "IsTheTalentWillingToMoveNearYourPlaceOfBusinessYes"
when
    qa : QuestionWithAnswer(getQuestion() == "Is the talent willing to move near your place of business?", getAnswer() == Helper.NO)
then
    QuestionWithAnswer newQuestion = new QuestionWithAnswer("Better keep the talent happy");
    newQuestion.setEndLeaf();
    insert(newQuestion);
end
